### ISSUE TITLE
Could you change the primitive type wrappers to array classes?

### ISSUE THREAD

**Issue by ciarrapeters** [gouldk/arrayInterface#11]
In class we talked about how having array types like intArray, floatArray, boolArray are faster and probably a better way to handle primitives instead of wrappers. Do you think you could implement these instead?

Basically these would look just like the Array class but instead of having parameters as type Object, they would be of type int (or other primitive) where appropriate. 

Thanks!

**Comment by ciarrapeters** [comment]
If you give us PR access, we can just change this ourselves and if you guys like it you can merge it in. As it stands now, when we try to push to a branch on your repo, it says we are denied

**Comment by BilobedCarton** [comment]
I added primitive type array interfaces. I'll let Kyle (my partner who owns this repo) know he should give you PR access because apparently I can't.

Have fun filling in the interfaces!
