### ISSUE TITLE
Design spec for array

### ISSUE THREAD

**Issue by ciarrapeters** [gouldk/arrayInterface#13]
Hey sorry, we _just_ noticed this as we were reading through the assignment for what we thought would be one last time. It says `Arrays should grow when values are pushed back, and otherwise support reads and writes.` To fix this, since you guys are going for a fixed size array api, we think you could just add a push() method that takes an object to add. We can then just call resize and set to push the object back and grow the array. Everything else would stay the same. What do you guys think?

**Comment by BilobedCarton** [comment]
Resolved! Added a push method that should grow the array and add the value.
