### ISSUE TITLE
Access to repo to make PR

### ISSUE THREAD

**Issue by ciarrapeters** [gouldk/arrayInterface#14]
We modified a bit of the code to fix some compiler issues in the test-array.cpp file. We also ended up changing the interface a bit for the primitive Arrays to inherit from Object instead of Array. This is because we found we would still need to use primitive Wrappers if we inherited from Array, since Array uses Objects.
We tried checking out a branch and pushing it to this repo to make a PR, but it still says:
![image](https://user-images.githubusercontent.com/17356801/73466846-6e962600-4350-11ea-8942-4f6683e58748.png)
Would you be able to give us access to the repo so you won't have to write out all this code if you agree with our changes?

Thank you!

**Comment by BilobedCarton** [comment]
You guys should be all set to make a pr.

**Comment by BilobedCarton** [comment]
If that doesn't work, try forking the repo and then making a pr for the fork?
