### ISSUE TITLE
Push() purpose statement intention?

### ISSUE THREAD

**Issue by ciarrapeters** [gouldk/arrayInterface#6]
Do you intend for push() to "Add the given object to the next available index" OR "at the end of the array". For example, in your test_remove() test, you make an Array of size 7, then only add an element at index 3. What would be the "next available index"? Would it be 0 (presumably an empty slot in the array), 4 (following the element you just placed at 3), or 7 (the size of the array). The test and spec seem to conflict a bit.

```
/**
 * @brief      Tests the remove function for Array
 */
void test_remove() {
	Array* arr = new Array(7);
	Object* obj = new Object();
	arr->set(obj, 3);
	assert(obj->equals(arr->remove(3)));
	assert(arr->get(3) == NULL);
	delete(obj);
	delete(arr);
}
```
Thank you!

**Comment by ciarrapeters** [comment]
After reading through some more tests, we think we understand what you guys are going for in your array implementation. Do you still mean to have "spaces" in your array (i.e. when you remove/delete, you don't change the size of the array, you are just deleting the element at that array). And do you mean to initialize everything to nullptr? Like if the array is initialized to size 5, are all the elements nullptr?

**Comment by ciarrapeters** [comment]
We still have the question though for push:
Say we have an array of size 3, and we have an element at index 1. Let's say we want to push another element onto the array. If we put it at the index which is the length of the array, this would overwrite the element that is already there (index 1). What index would we place this new element at?

**Comment by BilobedCarton** [comment]
I've removed push since it isn't in the scope of a fixed size array.
Elements can be null and are counted as contained in the array.
