### ISSUE TITLE
Delete(arr) breaking tests?

### ISSUE THREAD

**Issue by ciarrapeters** [gouldk/arrayInterface#8]
In your tests, you delete the array variables that you create:
```
void test_constructor_length() {
	Array* arr = new Array(20);
	assert(arr != NULL);
	assert(arr->length() == 20);
	delete(arr);
}
```
This is causing a malloc error when we try to run the tests. Would you be able to explain why you included the delete in there?

Thank you!

**Comment by BilobedCarton** [comment]
When initialising a variable one should always delete it when it becomes no longer necessary. I’m going to bet the issue is in the destructor you implemented for array. We could remove those delete calls but that would lead to a (albeit small) memory leak.

**Comment by ciarrapeters** [comment]
Ah, yes! Thank you. We had a syntax error in our destructor. We tried to do `delete array_` instead of `delete [] array_`

Thanks!
