### ISSUE TITLE
What happens if we try to push an element on a full array?

### ISSUE THREAD

**Issue by ciarrapeters** [gouldk/arrayInterface#9]
What happens if we try to push an element on a full array?
For example:
`array = [object1, object2, object3]`
if we call array->push(object4), should we allocate more space by resize()? Or are you trying to make this a fixed size array?

**Comment by BilobedCarton** [comment]
I've made it more clear that this is a fixed size array.
remove(idx) has been replaced with clear(idx).
I've also added a clear_all() function to clear all indices.
